### ISSUE TITLE
Curious about the awesome work you have done in this course

### ISSUE THREAD

**Issue by Fuaad110** [serebrov/udacity_hadoop_intro#1]
Hello sir,
I need to know the benefits of the tasks which you have done in this course . I mean how anyone like forum moderators will capitalize on such type of extracted information ??? which is as follow
1-List of students per thread
2-Finding Top Ten Tags.
3- Student Timings i.e. at which they are most active
4-Co-relation between question and answer.

Sir kindly please reply soon. Its urgent. Waiting for your reply

Regards.

**Comment by serebrov** [comment]
Sorry, I don't really understand the question nor the reason you are asking me about this. Probably you can address this to udacity course authors.
